### ISSUE TITLE
Extract Ember-Addon stuff into a shim

### ISSUE THREAD

**Issue by mixonic** [bustlelabs/mobiledoc-dom-renderer#10]
Per discussion on https://github.com/bustlelabs/mobiledoc-dom-renderer/pull/9, the ember-addon requirements should be extracted into a shim library.

**Comment by bantic** [comment]
broccoli-funnel is gone. the ember addon is now in a separate repo: https://github.com/bustlelabs/ember-mobiledoc-dom-renderer
