### ISSUE TITLE
Markup Element Renderer

### ISSUE THREAD

**Issue by gdub22** [bustlelabs/mobiledoc-dom-renderer#24]
The recent API addition of `sectionElementRenderer` works great for customizing how sections are rendered.  It would be great to add this functionality to markups too.  For example, adding a target or title to link elements, adding a className to italic elements, etc.

I see several approaches here:
- a new API method (con: adds more surface area)
- a unified API to custom render sections & markups (blocker: markup tag names are currently private)
- render markups as atoms and allow customization via the current atom api (unknown complexity)

**Comment by bantic** [comment]
closed by #32
