### ISSUE TITLE
Renders "pull-quote" as `<pull-quote` instead of `<div class="pull-quote"`

### ISSUE THREAD

**Issue by bantic** [bustlelabs/mobiledoc-dom-renderer#26]
See https://github.com/fusion2004/mobiledoc-dom-renderer-many-divs/commit/752aa1513b6f8985c2c05352b1835356ae380939

cc @fusion2004 — If you want to submit a PR for this using the code ^ I would be happy to accept it. Otherwise I'll fix this soon.

**Comment by bantic** [comment]
referenced by https://github.com/bustlelabs/mobiledoc-kit/issues/342#issuecomment-194860176

**Comment by fusion2004** [comment]
Sure! I can submit a PR later today.

**Comment by bantic** [comment]
@fusion2004 Thanks for reporting. I was halfway to making the tests pass when I was looking into it so went ahead and pushed the PR. :)

Released in v0.4.1
